# Generated by Django 2.1 on 2018-10-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicles',
            options={'managed': False, 'ordering': ('make',)},
        ),
    ]
